generate_config:
  generate_mode: database
  database_name: test_db
  host: localhost
  port: 3306
  username: root
  password: 200487
  all_tables: false
  table_names:
    - t_feedback_task
    - t_artifact

generate_option:
  # 输出路径
  output_path: ~/dev/model_infrax/output

  # 是否将所有模型放在一个文件中
  all_model_in_one_file: false

  # 所有模型放在一个文件中的文件名
  all_model_in_one_file_name: model.go

  # 只为有索引的字段生成 infrax 方法
  crud_only_idx: false

  # go 的 package 映射
  package_name:
    model_package: model
    dao_package: dao
    tool_package: tool