generate_config:
  # 生成模式: database(从数据库解析) 或 statement(从SQL文件解析)
  generate_mode: statement
  
  # database 模式配置
  database_name: test_db
  host: localhost
  port: 3306
  username: root
  password: 200487
  
  # statement 模式配置
  sql_file_path: ~/dev/model_infrax/assets/schema.sql
  
  # 通用配置
  all_tables: false
  table_names:
    - t_session_step

generate_option:
  # 输出路径
  output_path: ~/dev/model_infrax/output

  # 是否将所有模型放在一个文件中
  all_model_in_one_file: false

  # 所有模型放在一个文件中的文件名
  all_model_in_one_file_name: model.go

  # 只为有索引的字段生成 infrax 方法
  crud_only_idx: false

  # go 的 package 映射
  package_name:
    po_package: model/entity
    dto_package: model/query
    vo_package: model/view
    dao_package: dao
    tool_package: tool

  # 使用框架, 为空时为 gorm 原生
  use_framework: itea-go